services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.9
    container_name: nginx-proxy
    restart: unless-stopped
    environment:
      - HTTPS_METHOD=redirect
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    networks:
      - kali-net

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/acme:/etc/acme.sh
    healthcheck:
      test: ["CMD", "pgrep", "bash"]
      interval: 120s
      timeout: 10s
      retries: 3
    networks:
      - kali-net

networks:
  kali-net:
    external: true
